"""initial_schema

Revision ID: ac6114e4f743
Revises: 
Create Date: 2026-07-27 00:24:03.453450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6114e4f743'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_finance_owners_id'), 'finance_owners', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('finance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('default_interest_method', sa.String(length=20), nullable=False),
    sa.Column('default_interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_loan_duration', sa.Integer(), nullable=False),
    sa.Column('default_grace_period', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('maturity_alert_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_settings_finance_owner_id'), 'finance_settings', ['finance_owner_id'], unique=True)
    op.create_index(op.f('ix_finance_settings_id'), 'finance_settings', ['id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_principal_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_interest_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_method', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('interest_start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parent_loan_id', sa.Integer(), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('waived_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('settlement_reason', sa.String(length=255), nullable=True),
    sa.Column('closure_type', sa.String(length=20), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_interest_calculated_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ),
    sa.ForeignKeyConstraint(['parent_loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_table('loan_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_loan_id', sa.Integer(), nullable=False),
    sa.Column('new_loan_id', sa.Integer(), nullable=True),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('renewal_type', sa.String(length=20), nullable=False),
    sa.Column('old_due_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=False),
    sa.Column('old_interest_method', sa.String(length=20), nullable=False),
    sa.Column('new_interest_method', sa.String(length=20), nullable=False),
    sa.Column('old_interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_interest_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding_interest', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('renewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_renewals_finance_owner_id'), 'loan_renewals', ['finance_owner_id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_id'), 'loan_renewals', ['id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_new_loan_id'), 'loan_renewals', ['new_loan_id'], unique=False)
    op.create_index(op.f('ix_loan_renewals_old_loan_id'), 'loan_renewals', ['old_loan_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_owner_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['finance_owner_id'], ['finance_owners.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_loan_renewals_old_loan_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_new_loan_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_id'), table_name='loan_renewals')
    op.drop_index(op.f('ix_loan_renewals_finance_owner_id'), table_name='loan_renewals')
    op.drop_table('loan_renewals')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_finance_settings_id'), table_name='finance_settings')
    op.drop_index(op.f('ix_finance_settings_finance_owner_id'), table_name='finance_settings')
    op.drop_table('finance_settings')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_finance_owners_id'), table_name='finance_owners')
    op.drop_table('finance_owners')
    # ### end Alembic commands ###
